name: Test GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a simple command
        run: echo "Hello, GitHub Actions!"
