name: Run Tests

on:
  pull_request:
    branches:
      - master
      - main
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests and Save Output
        run: npm test -- --coverage > testOutput.txt

      - name: Display Test Output
        run: cat testOutput.txt

      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const testOutput = fs.readFileSync('testOutput.txt', 'utf8');
            const github = require('@actions/github');
            const { context } = github;
            const client = github.getOctokit(process.env.GITHUB_TOKEN);

            const comment = `
            # Automated Test Report

            ## Test Results

            \`\`\`
            ${testOutput}
            \`\`\`

            ## Test Coverage

            Test coverage report: https://codecov.io/gh/${context.repo.owner}/${context.repo.name}/commit/${context.payload.pull_request.head.sha}
            `;

            client.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: context.payload.pull_request.number,
              body: comment
            }).then(() => console.log('Comment created successfully.'))
            .catch(error => console.error('Error creating comment:', error));
