name: Run Tests and Comment Coverage on PR

on:
  pull_request:
    branches:
      - master
      - main
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests with Coverage
        run: |
          npm test -- --coverage --coverageReporters=text-summary > coverage.txt

      - name: Output Coverage to Console
        run: cat coverage.txt

      - name: Comment on PR with Coverage
        if: github.event_name == 'pull_request'
        run: |
          COVERAGE=$(cat coverage.txt)
          COMMENT="### Jest Test Coverage Report\n\`\`\`\n$COVERAGE\n\`\`\`"
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\":\"$COMMENT\"}" \
            "${{ github.event.pull_request.comments_url }}"
